<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="FB_BagCompactor" Id="{8355ad32-ac34-4e65-996a-35b6bf3aedd4}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_BagCompactor
VAR_INPUT
  ams_net_id: STRING;
END_VAR
VAR_OUTPUT
END_VAR
VAR
  status: BagMachineStatus;
  error_code: UINT;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="compact_bag" Id="{467a6aeb-1750-4e77-8ae9-97ca0fe84a75}">
      <Declaration><![CDATA[{attribute 'TcRpcEnable'}
METHOD PUBLIC compact_bag : BOOL
VAR_INPUT

END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_BagCompactor">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="FB_BagCompactor.compact_bag">
      <LineId Id="45" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>